name: Pull Request Validation

on:
  pull_request:
    branches: [develop, main]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Basic code check
      run: |
        python -m py_compile src/unified_dashboard.py
        python -m py_compile start_dashboard.py
        
    - name: Validate documentation
      run: |
        [ -s README.md ] || exit 1
        grep -q "Quick Start" README.md || exit 1
